In [2]:
# Importing necessary library
import numpy as np

In [3]:


# Test 1 scores matrix
# Rows represent students, columns represent subjects
test1_scores = np.array([
    [80, 50],  # Student 1
    [54, 67],  # Student 2
    [90, 80]   # Student 3
])

# Test 2 scores matrix
# Rows represent students, columns represent subjects
test2_scores = np.array([
    [90, 80],  # Student 1
    [74, 50],  # Student 2
    [80, 90]   # Student 3
])

In [5]:
# Subtracting Test 1 from Test 2 to find the difference matrix
difference = test2_scores - test1_scores

In [6]:
# Calculating the sum across the first axis (sum for each subject)
sum_across_axis = np.sum(difference, axis=0)

In [7]:
# Displaying results
print("Test 1 Scores Matrix:\n", test1_scores)
print("Test 2 Scores Matrix:\n", test2_scores)
print("Difference Matrix (Test 2 - Test 1):\n", difference)
print("Sum across the first axis (sum for each subject):\n", sum_across_axis)

Test 1 Scores Matrix:
 [[80 50]
 [54 67]
 [90 80]]
Test 2 Scores Matrix:
 [[90 80]
 [74 50]
 [80 90]]
Difference Matrix (Test 2 - Test 1):
 [[ 10  30]
 [ 20 -17]
 [-10  10]]
Sum across the first axis (sum for each subject):
 [20 23]
