In [14]:
import numpy as np

# Define a 3D vector
vector_3d = np.array([2, 3, .1])

# Define a 3x3 matrix for projection onto the XY-plane
matrix_3d = np.array([[1, 0, 0],
                      [0, 1, 0],
                      [0, 0, 0]])

# Print the vector and matrix
print("Vector:\n", vector_3d)
print("Matrix:\n", matrix_3d)

Vector:
 [2.  3.  0.1]
Matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 0]]


In [15]:
import numpy as np
import plotly.graph_objects as go

# Define two 3D vectors
vectors = [np.array([2, 3, 4]), np.array([2, 3, 1])]

# Define a 3x3 matrix for projection onto the XY-plane
matrix_3d = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])

# Define the XY-plane at Z=0
x_plane = np.linspace(-2, 3, 10)
y_plane = np.linspace(-2, 3, 10)
X_plane, Y_plane = np.meshgrid(x_plane, y_plane)
Z_plane = np.zeros_like(X_plane)

# Create a 3D plot with Plotly
fig = go.Figure()

# Loop over the vectors to add both original and projected versions
for i, vector_3d in enumerate(vectors):
    # Perform matrix-vector multiplication to project the vector onto the XY-plane
    projected_vector = matrix_3d @ vector_3d

    # Original vector in 3D
    fig.add_trace(go.Scatter3d(
        x=[0, vector_3d[0]],
        y=[0, vector_3d[1]],
        z=[0, vector_3d[2]],
        mode='lines+markers',
        marker=dict(size=5, color='blue'),
        line=dict(color='blue', width=5),
        name=f'Original Vector {i+1}'
    ))

    # Projected vector in 3D (onto the XY-plane)
    fig.add_trace(go.Scatter3d(
        x=[0, projected_vector[0]],
        y=[0, projected_vector[1]],
        z=[0, projected_vector[2]],
        mode='lines+markers',
        marker=dict(size=5, color='green'),
        line=dict(color='green', width=5),
        name=f'Projected Vector {i+1}'
    ))

# Add the XY-plane to the plot
fig.add_trace(go.Surface(
    x=X_plane, y=Y_plane, z=Z_plane,
    colorscale=[[0, 'red'], [1, 'red']],
    opacity=0.5,
    showscale=False,
    name='XY Plane'
))

# Update layout for visualization
fig.update_layout(
    scene=dict(
        xaxis_title='X-axis',
        yaxis_title='Y-axis',
        zaxis_title='Z-axis',
        aspectratio=dict(x=1, y=1, z=0.5)
    ),
    title="3D Vectors and Their Projections onto the XY Plane",
    showlegend=True
)

# Display the interactive plot
fig.show()

In [16]:
import numpy as np

# Define the vectors
vectors = [np.array([2, 3, 4]), np.array([2, 3, 0.1])]

# Define the projection matrix for the XY-plane
matrix_3d = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0]])

# Calculate the loss of information (Euclidean distance) for each vector
for i, vector_3d in enumerate(vectors):
    # Project the vector onto the XY-plane
    projected_vector = matrix_3d @ vector_3d

    # Calculate the Euclidean distance between the original and projected vectors
    loss_of_information = np.linalg.norm(vector_3d - projected_vector)

    # Display the result
    print(f"Original Vector {i+1}: {vector_3d}")
    print(f"Projected Vector {i+1}: {projected_vector}")
    print(f"Loss of Information (Euclidean Distance) for Vector {i+1}: {loss_of_information:.2f}\n")


Original Vector 1: [2 3 4]
Projected Vector 1: [2 3 0]
Loss of Information (Euclidean Distance) for Vector 1: 4.00

Original Vector 2: [2.  3.  0.1]
Projected Vector 2: [2. 3. 0.]
Loss of Information (Euclidean Distance) for Vector 2: 0.10

