In [1]:
# Importing necessary libraries
import numpy as np
import plotly.graph_objects as go

# Define a 3x3 matrix
matrix = np.array([[2, 1, 0],
                   [1, 2, 0],
                   [0, 0, 3]])

# Define 4 vectors, including one eigenvector
vectors = [
    np.array([1, 2, 1]),
    np.array([-1, 1, 2]),
    np.array([3, -1, 1]),
    np.array([0.70710678, 0.70710678, 0])
]

# Define colors for each pair
colors = ['red', 'blue', 'purple', 'green']  # Distinct color for each pair








In [2]:

# Create a figure for original vectors with labels at the end
fig = go.Figure()

# Plot the original vectors with labels at the end
for i, vector in enumerate(vectors):
    fig.add_trace(go.Scatter3d(
        x=[0, vector[0]],
        y=[0, vector[1]],
        z=[0, vector[2]],
        mode='lines+markers+text',
        marker=dict(size=4),
        line=dict(width=5, color=colors[i]),  # Use distinct color for each vector
        text=[None, f"Vector {i + 1} "],  # Label only at the endpoint
        textposition="top right",  # Position at the end of the vector
        textfont=dict(size=10)
    ))

# Add layout for better visualization
fig.update_layout(
    title="Original Vectors",
    scene=dict(
        xaxis=dict(range=[-5, 5], title='X-axis'),
        yaxis=dict(range=[-5, 5], title='Y-axis'),
        zaxis=dict(range=[-5, 5], title='Z-axis')
    )
)
fig.show()


In [3]:

# Create a figure for transformed vectors with labels at the end and original vectors as dotted lines
fig_transformed = go.Figure()

# Plot the transformed vectors with labels at the end
for i, vector in enumerate(vectors):
    transformed_vector = matrix @ vector
    fig_transformed.add_trace(go.Scatter3d(
        x=[0, transformed_vector[0]],
        y=[0, transformed_vector[1]],
        z=[0, transformed_vector[2]],
        mode='lines+markers+text',
        marker=dict(size=4),
        line=dict(width=5, color=colors[i]),  # Same color for the transformed pair
        text=[None, f"Transformed Vector {i + 1}"],  # Label at the end
        textposition="top right",  # Position text at the endpoint
        textfont=dict(size=10)
    ))

    # Plot the original vector as a dotted line in the transformed plot
    fig_transformed.add_trace(go.Scatter3d(
        x=[0, vector[0]],
        y=[0, vector[1]],
        z=[0, vector[2]],
        mode='lines',
        line=dict(width=3, color=colors[i], dash='dot'),  # Dotted line style
        showlegend=False  # Hide legend for dotted lines
    ))

# Add layout for better visualization
fig_transformed.update_layout(
    title="Transformed Vectors with Original Vectors as Dotted Lines",
    scene=dict(
        xaxis=dict(range=[-10, 10], title='X-axis'),
        yaxis=dict(range=[-10, 10], title='Y-axis'),
        zaxis=dict(range=[-10, 10], title='Z-axis')
    )
)
fig_transformed.show()



In [4]:
# Create a figure for only the eigenvector and its transformed version
fig_eigen = go.Figure()
eigenvector = np.array([0.70710678, 0.70710678, 0])

# Plot the original eigenvector with label at the endpoint
fig_eigen.add_trace(go.Scatter3d(
    x=[0, eigenvector[0]],
    y=[0, eigenvector[1]],
    z=[0, eigenvector[2]],
    mode='lines+markers+text',
    marker=dict(size=6),
    line=dict(width=8, color='green'),
    text=[None, "Eigenvector (Original)"],  # Label only at the endpoint
    textposition="top right",  # Position at the end of the vector
    textfont=dict(size=10)
))

# Plot the transformed eigenvector with label at the endpoint
transformed_eigenvector = matrix @ eigenvector
fig_eigen.add_trace(go.Scatter3d(
    x=[0, transformed_eigenvector[0]],
    y=[0, transformed_eigenvector[1]],
    z=[0, transformed_eigenvector[2]],
    mode='lines+markers+text',
    marker=dict(size=6),
    line=dict(width=8, color='blue'),
    text=[None, "Eigenvector (Transformed)"],  # Label only at the endpoint
    textposition="top right",  # Position at the end of the vector
    textfont=dict(size=10)
))

# Add layout for better visualization
fig_eigen.update_layout(
    title="Eigenvector and Transformed Eigenvector",
    scene=dict(
        xaxis=dict(range=[-5, 5], title='X-axis'),
        yaxis=dict(range=[-5, 5], title='Y-axis'),
        zaxis=dict(range=[-5, 5], title='Z-axis')
    )
)
fig_eigen.show()

In [ ]:
# Calculate the eigenvalues and eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
eigenvectors

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [ ]:
eigenvalues

array([3., 1., 3.])

An eigenvalue is the amount by which the eigenvector is stretched or compressed.

In [ ]:
# Demonstrate the matrix-vector multiplication for each eigenvector
for i in range(len(eigenvalues)):
    eigenvalue = eigenvalues[i]
    eigenvector = eigenvectors[:, i]

    # Calculate A * eigenvector
    matrix_vector_product = matrix @ eigenvector

    # Calculate eigenvalue * eigenvector
    scaled_eigenvector = eigenvalue * eigenvector

    # Display results
    print(f"Eigenvalue {i+1}: {eigenvalue}")
    print(f"Eigenvector {i+1}: {eigenvector}")
    print("A * Eigenvector:")
    print(matrix_vector_product)
    print("Eigenvalue * Eigenvector:")
    print(scaled_eigenvector)
    print("\n")

Eigenvalue 1: 3.0
Eigenvector 1: [0.70710678 0.70710678 0.        ]
A * Eigenvector:
[2.12132034 2.12132034 0.        ]
Eigenvalue * Eigenvector:
[2.12132034 2.12132034 0.        ]


Eigenvalue 2: 1.0
Eigenvector 2: [-0.70710678  0.70710678  0.        ]
A * Eigenvector:
[-0.70710678  0.70710678  0.        ]
Eigenvalue * Eigenvector:
[-0.70710678  0.70710678  0.        ]


Eigenvalue 3: 3.0
Eigenvector 3: [0. 0. 1.]
A * Eigenvector:
[0. 0. 3.]
Eigenvalue * Eigenvector:
[0. 0. 3.]


