In [1]:
import numpy as np

# Define a square matrix
A = np.array([[4, 2],
              [1, 3]])

print("Original Matrix A:\n", A)

# 1. Eigen Decomposition (only for square matrices)
eigenvalues, eigenvectors = np.linalg.eig(A)
Lambda = np.diag(eigenvalues)  # Diagonal matrix of eigenvalues

# Reconstruct the matrix from Eigen Decomposition
A_reconstructed_eigen = eigenvectors @ Lambda @ np.linalg.inv(eigenvectors)

print("\nEigen Decomposition:")
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors (columns of P):\n", eigenvectors)
print("Reconstructed Matrix A from Eigen Decomposition:\n", A_reconstructed_eigen)

# 2. Singular Value Decomposition (SVD)
U, Sigma, Vt = np.linalg.svd(A)

# Convert Sigma to a diagonal matrix for reconstruction
Sigma_matrix = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(Sigma_matrix, Sigma)

# Reconstruct the matrix from SVD
A_reconstructed_svd = U @ Sigma_matrix @ Vt

print("\nSingular Value Decomposition (SVD):")
print("Left Singular Vectors (U):\n", U)
print("Singular Values (Sigma):\n", Sigma)
print("Right Singular Vectors (V^T):\n", Vt)
print("Reconstructed Matrix A from SVD:\n", A_reconstructed_svd)


Original Matrix A:
 [[4 2]
 [1 3]]

Eigen Decomposition:
Eigenvalues:
 [5. 2.]
Eigenvectors (columns of P):
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
Reconstructed Matrix A from Eigen Decomposition:
 [[4. 2.]
 [1. 3.]]

Singular Value Decomposition (SVD):
Left Singular Vectors (U):
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
Singular Values (Sigma):
 [5.11667274 1.95439508]
Right Singular Vectors (V^T):
 [[-0.76775173 -0.64074744]
 [-0.64074744  0.76775173]]
Reconstructed Matrix A from SVD:
 [[4. 2.]
 [1. 3.]]
