In [1]:
# Basic Operations with Vectors and Matrices in NumPy
# This notebook covers exercises on defining vectors and matrices, summing along an axis,
# and performing matrix-vector and matrix-matrix multiplication.

# Import numpy library
import numpy as np

In [2]:
# Exercise 1: Define Vectors
# In this exercise, we will define two vectors 'a' and 'b' with specific values.

# Define vector 'a' with values [1, 2, 3]
a = np.array([1, 2, 3])

# Define another vector 'b' with values [4, 5, 6]
b = np.array([4, 5, 6])

# Display the vectors
print("Vector a:", a)
print("Vector b:", b)

Vector a: [1 2 3]
Vector b: [4 5 6]


In [3]:
# Exercise 2: Define Matrices
# Here, we'll define two matrices 'M' and 'N' with specific values.

# Define a 2x3 matrix 'M'
M = np.array([[1, 2, 3], [4, 5, 6]])

# Define a 3x2 matrix 'N'
N = np.array([[1, 4], [2, 5], [3, 6]])

# Display the matrices
print("Matrix M:\n", M)
print("Matrix N:\n", N)

Matrix M:
 [[1 2 3]
 [4 5 6]]
Matrix N:
 [[1 4]
 [2 5]
 [3 6]]


In [4]:
# Exercise 3: Sum Along an Axis
# We'll calculate the sum of elements along different axes in matrix 'M'.

# Sum of M along axis 0 (column-wise sum)
col_sum = np.sum(M, axis=0)

# Sum of M along axis 1 (row-wise sum)
row_sum = np.sum(M, axis=1)

# Display the results
print("Column-wise sum of M:", col_sum)
print("Row-wise sum of M:", row_sum)

Column-wise sum of M: [5 7 9]
Row-wise sum of M: [ 6 15]


In [5]:
# Exercise 4: Matrix-Vector Multiplication
# Define a new vector 'c' and perform matrix-vector multiplication with 'M'.

# Define vector 'c' with values [1, 0, -1]
c = np.array([1, 0, -1])

# Multiply matrix M by vector c
d = np.dot(M, c)

# Display the result of the multiplication
print("Result of M * c:", d)

Result of M * c: [-2 -2]


In [6]:
# Exercise 5: Matrix-Matrix Multiplication
# Multiply matrices 'M' and 'N' to produce a new matrix.

# Perform matrix-matrix multiplication of M and N
result = np.dot(M, N)

# Display the result
print("Result of M * N:\n", result)

Result of M * N:
 [[14 32]
 [32 77]]
