# **Covariance and correlation**

In [1]:
import numpy as np
import pandas as pd

First, we load the dataset that contains heights (in inches) and weights (in lbs) of 10000 individuals.

In [2]:
data = pd.read_csv('https://github.com/evgeniyako-edu/datasets/raw/main/weight-height.csv')
data.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
data.shape

(10000, 3)

Height and weight are probably related. What is the covariance between them? You can use the $\texttt{np.cov()}$ function to estimate covariance matrix.

In [4]:
np.cov(data["Height"], data["Weight"])

array([[  14.80347264,  114.24265645],
       [ 114.24265645, 1030.95185544]])

And what is the correlation coefficient between the two?

In [5]:
np.corrcoef(data["Height"], data["Weight"])

array([[1.       , 0.9247563],
       [0.9247563, 1.       ]])

Now, let's convert the measurements into the metric system (meters and kilos):

In [6]:
# 1 inch = 0.0254 meters
# 1 pound = 0.45359237 kg

# TODO: your code here
data['Height'] = data['Height']*0.0254
data['Weight'] = data['Weight']*0.4535 
data

Gender    Height      Weight
0       Male  1.875714  109.698731
1       Male  1.747060   73.607799
2       Male  1.882397   96.477978
3       Male  1.821967   99.789260
4       Male  1.774998   93.579635
...      ...       ...         ...
9995  Female  1.680785   62.028575
9996  Female  1.703506   77.488595
9997  Female  1.622247   58.263557
9998  Female  1.753470   74.307091
9999  Female  1.573384   51.539868

[10000 rows x 3 columns]

Now, compute covariance and correlation between the transformed heights and weights. What do you observe?

In [8]:
# TODO: your code here
np.cov(data.Height, data.Weight)

array([[9.55060841e-03, 1.31594974e+00],
       [1.31594974e+00, 2.12027878e+02]])

In [10]:
# TODO: your code here
corr_matrix = np.corrcoef(data.Height, data.Weight)
corr_matrix

array([[1.       , 0.9247563],
       [0.9247563, 1.       ]])